-- Augura Platform — seed
-- À appliquer APRÈS functions.sql et AVANT policies.sql (avant l'activation RLS).
--
-- Intentionnellement vide : plus de données de démonstration. La base démarre sans
-- contenu ; les vraies données (cohortes, corpus, résultats de bootstrap) sont
-- importées via les scripts dédiés (P3/P5) ou créées par l'application en mode réel.
-- Le front rend des états vides tant qu'aucune donnée réelle n'est présente.
