/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents/dag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dag */
        post: operations["dag_agents_dag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gaps */
        post: operations["gaps_agents_gaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/profiling/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profiling Stream */
        post: operations["profiling_stream_agents_profiling_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/variable-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Variable Check */
        post: operations["variable_check_agents_variable_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin */
        get: operations["admin_analytics_admin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_corpus_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed */
        get: operations["feed_corpus_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_corpus_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_corpus_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        /** Create Dataset */
        post: operations["create_dataset_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/cohorts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cohorts */
        get: operations["list_cohorts_datasets_cohorts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/cohorts/{cohort_name}/biomarkers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cohort Biomarkers */
        get: operations["cohort_biomarkers_datasets_cohorts__cohort_name__biomarkers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/cohorts/{cohort_name}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cohort Members */
        get: operations["cohort_members_datasets_cohorts__cohort_name__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Columns */
        get: operations["list_columns_datasets__dataset_id__columns_get"];
        /** Replace Columns */
        put: operations["replace_columns_datasets__dataset_id__columns_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Generate */
        post: operations["generate_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Status */
        get: operations["get_job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Simulation */
        post: operations["create_simulation_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Power */
        post: operations["power_simulations_power_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results */
        get: operations["results_simulations_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Studies */
        get: operations["list_studies_studies_get"];
        put?: never;
        /** Create Study */
        post: operations["create_study_studies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studies/{study_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Study */
        get: operations["get_study_studies__study_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studies/{study_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_studies__study_id__state_get"];
        /** Put State */
        put: operations["put_state_studies__study_id__state_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminStats */
        AdminStats: {
            /** By Type */
            by_type: {
                [key: string]: number;
            };
            /** Recent */
            recent: components["schemas"]["RecentEvent"][];
            /** Total Events */
            total_events: number;
            /** Unique Users */
            unique_users: number;
            /** Window Days */
            window_days: number;
        };
        /** CohortBiomarkerOut */
        CohortBiomarkerOut: {
            /** Adherence Pct */
            adherence_pct?: number | null;
            /** Hba1C Pct */
            hba1c_pct?: number | null;
            /** Hs Crp Mgl */
            hs_crp_mgl?: number | null;
            /** Ldl Mgdl */
            ldl_mgdl?: number | null;
            /** Member Id */
            member_id: string;
            /** Timepoint Months */
            timepoint_months: number;
        };
        /** CohortMemberOut */
        CohortMemberOut: {
            /** Age */
            age?: number | null;
            /** Bmi */
            bmi?: number | null;
            /** Country */
            country?: string | null;
            /** Engagement Group */
            engagement_group?: string | null;
            /** Member Id */
            member_id: string;
            /** Sex */
            sex?: string | null;
        };
        /** CohortSummary */
        CohortSummary: {
            /** Cohort Name */
            cohort_name: string;
            /** N Members */
            n_members: number;
        };
        /** ColumnIn */
        ColumnIn: {
            /** Confidence */
            confidence?: number | null;
            /** Final Canonical Id */
            final_canonical_id?: string | null;
            /** Final Role */
            final_role?: string | null;
            /** Max */
            max?: number | null;
            /** Min */
            min?: number | null;
            /** N Distinct */
            n_distinct?: number | null;
            /** N Non Null */
            n_non_null?: number | null;
            /** N Total */
            n_total?: number | null;
            /** Name */
            name: string;
            /** Null Pct */
            null_pct?: number | null;
            /** Proposed Canonical Id */
            proposed_canonical_id?: string | null;
            /** Proposed Group */
            proposed_group?: string | null;
            /** Proposed Role */
            proposed_role?: string | null;
            /** Rationale */
            rationale?: string | null;
            /** Sheet */
            sheet: string;
            /** Top Values */
            top_values?: unknown[] | null;
            /**
             * User Decision
             * @default pending
             */
            user_decision: string;
            /** Value Kind */
            value_kind?: string | null;
        };
        /** ColumnMatch */
        ColumnMatch: {
            /**
             * Alternatives
             * @default []
             */
            alternatives: string[];
            /** Column */
            column: string;
            /** Confidence */
            confidence: number;
            /** Proposed Canonical Id */
            proposed_canonical_id?: string | null;
            /** Proposed Group */
            proposed_group: string;
            /** Proposed Role */
            proposed_role: string;
            /** Rationale */
            rationale: string;
            /** Sheet */
            sheet: string;
        };
        /** ColumnOut */
        ColumnOut: {
            /** Confidence */
            confidence?: number | null;
            /** Final Canonical Id */
            final_canonical_id?: string | null;
            /** Final Role */
            final_role?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Max */
            max?: number | null;
            /** Min */
            min?: number | null;
            /** N Distinct */
            n_distinct?: number | null;
            /** N Non Null */
            n_non_null?: number | null;
            /** N Total */
            n_total?: number | null;
            /** Name */
            name: string;
            /** Null Pct */
            null_pct?: number | null;
            /** Proposed Canonical Id */
            proposed_canonical_id?: string | null;
            /** Proposed Group */
            proposed_group?: string | null;
            /** Proposed Role */
            proposed_role?: string | null;
            /** Rationale */
            rationale?: string | null;
            /** Sheet */
            sheet: string;
            /** Top Values */
            top_values?: unknown[] | null;
            /** User Decision */
            user_decision: string;
            /** Value Kind */
            value_kind?: string | null;
        };
        /** ColumnStat */
        ColumnStat: {
            /** Column */
            column: string;
            /** Max */
            max?: number | null;
            /** Min */
            min?: number | null;
            /** N Distinct */
            n_distinct?: number | null;
            /** N Non Null */
            n_non_null?: number | null;
            /** N Total */
            n_total?: number | null;
            /** Null Pct */
            null_pct?: number | null;
            /** Top Values */
            top_values?: unknown[] | null;
            /** Value Kind */
            value_kind?: string | null;
        };
        /** ColumnsPut */
        ColumnsPut: {
            /** Columns */
            columns: components["schemas"]["ColumnIn"][];
        };
        /** CoverageCell */
        CoverageCell: {
            /** Doc Count */
            doc_count: number;
            /** Evidence Type */
            evidence_type: string;
            /** Gap Score */
            gap_score: number;
            /** Gap Severity */
            gap_severity: string;
            /** Jurisdiction */
            jurisdiction: string;
        };
        /** CoverageMeta */
        CoverageMeta: {
            /** Evidence Types */
            evidence_types: string[];
            /** Jurisdictions */
            jurisdictions: string[];
            /** Total Docs */
            total_docs: number;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /** Gap Pills */
            gap_pills: components["schemas"]["GapPill"][];
            /** Matrix */
            matrix: components["schemas"]["CoverageCell"][];
            meta: components["schemas"]["CoverageMeta"];
        };
        /** DagEdge */
        DagEdge: {
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /** DagNode */
        DagNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Measured */
            measured: boolean;
            /** Rationale */
            rationale?: string | null;
            /** Role */
            role: string;
        };
        /** DagRequest */
        DagRequest: {
            /**
             * Candidate Outcomes
             * @default []
             */
            candidate_outcomes: string[];
            /** Dataset Variables */
            dataset_variables?: {
                [key: string]: unknown;
            } | null;
            /**
             * Gap Variables
             * @default []
             */
            gap_variables: {
                [key: string]: unknown;
            }[];
            /** Intervention */
            intervention: string;
            /** Outcome */
            outcome: string;
            /** Population */
            population?: string | null;
            /** Product Docs */
            product_docs?: string | null;
            /** Selected Outcome */
            selected_outcome?: string | null;
            /** Study Type */
            study_type?: string | null;
        };
        /** DagResponse */
        DagResponse: {
            /** Adjustment Set */
            adjustment_set: string[];
            /**
             * Collider Ids
             * @default []
             */
            collider_ids: string[];
            /** Edges */
            edges: components["schemas"]["DagEdge"][];
            /** Nodes */
            nodes: components["schemas"]["DagNode"][];
            /** Rationale */
            rationale: string;
        };
        /** DatasetCreate */
        DatasetCreate: {
            /** Name */
            name: string;
            /** Row Count */
            row_count?: number | null;
            /** Storage Path */
            storage_path?: string | null;
            /** Study Id */
            study_id?: string | null;
        };
        /** DatasetOut */
        DatasetOut: {
            /**
             * Column Count
             * @default 0
             */
            column_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Row Count */
            row_count?: number | null;
            /** Status */
            status: string;
            /** Storage Path */
            storage_path?: string | null;
            /** Study Id */
            study_id?: string | null;
        };
        /** DatasetQuestion */
        DatasetQuestion: {
            /** Answer */
            answer: string;
            /** Confidence */
            confidence: number;
            /**
             * Evidence Columns
             * @default []
             */
            evidence_columns: string[];
            /**
             * Options
             * @default []
             */
            options: string[];
            /** Question Code */
            question_code: string;
            /** Rationale */
            rationale?: string | null;
        };
        /** EstimatorPowerOut */
        EstimatorPowerOut: {
            /** Bias */
            bias: number;
            /** Ci Lower */
            ci_lower: number;
            /** Ci Upper */
            ci_upper: number;
            /** Effect */
            effect: number;
            /** Estimator */
            estimator: string;
            /** Mse */
            mse: number;
            /** Power */
            power: number;
            /** Variance */
            variance: number;
        };
        /** FeedDocument */
        FeedDocument: {
            /** Age Label */
            age_label?: string | null;
            /** Evidence Type */
            evidence_type?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is New
             * @default false
             */
            is_new: boolean;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Lifecycle */
            lifecycle?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Source Id */
            source_id: string;
            /** Summary */
            summary?: string | null;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /** FeedMeta */
        FeedMeta: {
            /** Total */
            total: number;
        };
        /** FeedResponse */
        FeedResponse: {
            /** Documents */
            documents: components["schemas"]["FeedDocument"][];
            meta: components["schemas"]["FeedMeta"];
        };
        /** GapPill */
        GapPill: {
            /** Doc Count */
            doc_count: number;
            /** Evidence Type */
            evidence_type: string;
            /** Gap Score */
            gap_score: number;
            /** Gap Severity */
            gap_severity: string;
            /** Jurisdiction */
            jurisdiction: string;
        };
        /** GapRequest */
        GapRequest: {
            /** Intervention */
            intervention: string;
            /**
             * Measured Variables
             * @default []
             */
            measured_variables: components["schemas"]["MeasuredVariable"][];
            /** Outcome */
            outcome: string;
            /** Population */
            population?: string | null;
            /** Selected Outcome */
            selected_outcome?: string | null;
        };
        /** GapResponse */
        GapResponse: {
            /** Missing Variables */
            missing_variables: components["schemas"]["MissingVariable"][];
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Study Id */
            study_id?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "protocol" | "report";
        };
        /** GeneratedDocumentCreated */
        GeneratedDocumentCreated: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: string;
        };
        /** GeneratedDocumentOut */
        GeneratedDocumentOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Storage Path */
            storage_path?: string | null;
            /** Study Id */
            study_id?: string | null;
            /** Type */
            type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobOut */
        JobOut: {
            /** Error */
            error?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Progress */
            progress: number;
            /** Result Ref */
            result_ref?: string | null;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /** MeasuredVariable */
        MeasuredVariable: {
            /** Column */
            column: string;
            /** Role */
            role?: string | null;
        };
        /** MissingVariable */
        MissingVariable: {
            /** Category */
            category: string;
            /** Column Hint */
            column_hint?: string | null;
            /** Name */
            name: string;
            /** Rationale */
            rationale: string;
            /** Role */
            role: string;
            /** Severity */
            severity: string;
        };
        /** PowerRequest */
        PowerRequest: {
            /**
             * Dropout
             * @default 0.2
             */
            dropout: number;
            /**
             * Effect
             * @default 0.3
             */
            effect: number;
            /** Estimators */
            estimators?: string[] | null;
            /** N */
            n?: number | null;
            /** Outcome */
            outcome?: string | null;
            /** Sigma */
            sigma?: number | null;
        };
        /** PowerResponse */
        PowerResponse: {
            /** Dropout */
            dropout: number;
            /** Effect */
            effect: number;
            /** Estimators */
            estimators: components["schemas"]["EstimatorPowerOut"][];
            /** N */
            n: number;
            /** Power Threshold */
            power_threshold: number;
            /** Sigma */
            sigma: number;
        };
        /** ProfilingRequest */
        ProfilingRequest: {
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
            /** Product Description */
            product_description?: string | null;
            /** System */
            system: string;
            /**
             * Tools
             * @default []
             */
            tools: {
                [key: string]: unknown;
            }[];
        };
        /** RecentEvent */
        RecentEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Type */
            event_type: string;
            /** Route */
            route?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** SearchHit */
        SearchHit: {
            /** Content */
            content: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Similarity */
            similarity: number;
            /** Source Id */
            source_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Filter
             * @default {}
             */
            filter: {
                [key: string]: string;
            };
            /**
             * Match Count
             * @default 20
             */
            match_count: number;
            /** Query Embedding */
            query_embedding: number[];
        };
        /** Sheet */
        Sheet: {
            /**
             * Column Stats
             * @default []
             */
            column_stats: components["schemas"]["ColumnStat"][];
            /**
             * Headers
             * @default []
             */
            headers: string[];
            /** Name */
            name: string;
            /**
             * Sample
             * @default []
             */
            sample: unknown[][];
        };
        /** SimulationRequest */
        SimulationRequest: {
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /** Study Id */
            study_id?: string | null;
        };
        /** SimulationResultOut */
        SimulationResultOut: {
            /** Ci Lower */
            ci_lower?: number | null;
            /** Ci Upper */
            ci_upper?: number | null;
            /** Cohort Name */
            cohort_name: string;
            /** Effect Size */
            effect_size?: number | null;
            /** Estimator */
            estimator: string;
            /** P Value */
            p_value?: number | null;
            /** Power */
            power?: number | null;
            /** Scenario */
            scenario: string;
        };
        /** SimulationRunCreated */
        SimulationRunCreated: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
        };
        /** SourceCount */
        SourceCount: {
            /** Count */
            count: number;
            /** Source Id */
            source_id: string;
        };
        /** SourcesResponse */
        SourcesResponse: {
            /** Sources */
            sources: components["schemas"]["SourceCount"][];
            /** Total */
            total: number;
        };
        /** StudyCreate */
        StudyCreate: {
            /** Category */
            category?: string | null;
            /** Framework */
            framework?: string | null;
            /** N Subjects */
            n_subjects?: number | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Tagline */
            tagline?: string | null;
        };
        /** StudyOut */
        StudyOut: {
            /** Category */
            category?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Framework */
            framework?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lead */
            lead?: string | null;
            /** N Subjects */
            n_subjects?: number | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Tagline */
            tagline?: string | null;
        };
        /** StudyStateOut */
        StudyStateOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** State */
            state: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
        };
        /** StudyStatePut */
        StudyStatePut: {
            /** State */
            state: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariableCheckRequest */
        VariableCheckRequest: {
            /**
             * Product Description
             * @default
             */
            product_description: string;
            /** Projectid */
            projectId?: string | null;
            /** Sheets */
            sheets: components["schemas"]["Sheet"][];
        };
        /** VariableCheckResponse */
        VariableCheckResponse: {
            /** Clinical Domain */
            clinical_domain?: string | null;
            /** Dataset Questions */
            dataset_questions?: components["schemas"]["DatasetQuestion"][] | null;
            /** Matches */
            matches: components["schemas"]["ColumnMatch"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dag_agents_dag_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gaps_agents_gaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profiling_stream_agents_profiling_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    variable_check_agents_variable_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariableCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_analytics_admin_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
        };
    };
    coverage_corpus_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
        };
    };
    feed_corpus_feed_get: {
        parameters: {
            query?: {
                jurisdiction?: string | null;
                evidence_type?: string | null;
                source_id?: string | null;
                lifecycle?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_corpus_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_corpus_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
        };
    };
    create_dataset_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cohorts_datasets_cohorts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortSummary"][];
                };
            };
        };
    };
    cohort_biomarkers_datasets_cohorts__cohort_name__biomarkers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cohort_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortBiomarkerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cohort_members_datasets_cohorts__cohort_name__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cohort_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_columns_datasets__dataset_id__columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_columns_datasets__dataset_id__columns_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnsPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocumentOut"][];
                };
            };
        };
    };
    generate_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocumentCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_simulation_simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    power_simulations_power_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PowerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PowerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_simulations_results_get: {
        parameters: {
            query?: {
                cohort_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_studies_studies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyOut"][];
                };
            };
        };
    };
    create_study_studies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_study_studies__study_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_studies__study_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_state_studies__study_id__state_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyStatePut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
