from typing import Any

import structlog
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from sqlalchemy.exc import SQLAlchemyError

log = structlog.get_logger(__name__)


class AppError(Exception):
    """Base application error. Subclass it, never raise it directly."""

    code: str = "app_error"
    http_status: int = 500
    title: str = "Application error"

    def __init__(self, detail: str, **context: Any) -> None:
        super().__init__(detail)
        self.detail = detail
        self.context = context


class NotFoundError(AppError):
    code = "not_found"
    http_status = 404
    title = "Resource not found"


class BadRequestError(AppError):
    code = "bad_request"
    http_status = 400
    title = "Bad request"


class UnauthorizedError(AppError):
    code = "unauthorized"
    http_status = 401
    title = "Unauthorized"


class ForbiddenError(AppError):
    code = "forbidden"
    http_status = 403
    title = "Forbidden"


class ConflictError(AppError):
    code = "conflict"
    http_status = 409
    title = "Conflict"


class PayloadTooLargeError(AppError):
    code = "payload_too_large"
    http_status = 413
    title = "Payload too large"


class UnsupportedMediaTypeError(AppError):
    code = "unsupported_media_type"
    http_status = 415
    title = "Unsupported media type"


def register_error_handlers(app: FastAPI) -> None:
    @app.exception_handler(AppError)
    async def handle_app_error(_request: Request, exc: AppError) -> JSONResponse:
        body: dict[str, Any] = {
            "type": f"https://augura.dev/errors/{exc.code}",
            "title": exc.title,
            "status": exc.http_status,
            "detail": exc.detail,
            "code": exc.code,
        }
        if exc.context:
            body["context"] = exc.context
        return JSONResponse(
            status_code=exc.http_status,
            content=body,
            media_type="application/problem+json",
        )

    @app.exception_handler(SQLAlchemyError)
    async def handle_db_error(_request: Request, exc: SQLAlchemyError) -> JSONResponse:
        # An unmapped database error (RLS violation, constraint, outage) would otherwise
        # surface as a raw 500 ABOVE the CORS middleware (generated by ServerErrorMiddleware):
        # the browser then reads it as "Failed to fetch" with no CORS header, hence no
        # message. By catching it here (ExceptionMiddleware, below CORS) the response
        # goes back through CORS and the frontend sees a real 500 error.
        log.exception("db_error", error=str(exc))
        return JSONResponse(
            status_code=500,
            content={
                "type": "https://augura.dev/errors/database_error",
                "title": "Database error",
                "status": 500,
                "detail": "the database operation failed",
                "code": "database_error",
            },
            media_type="application/problem+json",
        )

    @app.exception_handler(OSError)
    async def handle_storage_error(_request: Request, exc: OSError) -> JSONResponse:
        # Object-store failures (core.storage) raise OSError — FileNotFoundError when a
        # dataset file is missing (e.g. Modal's per-container ephemeral disk not holding a
        # file written by another container), or OSError when the Supabase Storage REST call
        # fails. Like the DB handler above, we map it BELOW the CORS middleware so the 500
        # keeps its CORS header; otherwise ServerErrorMiddleware emits a header-less 500 that
        # the browser surfaces as an opaque "Failed to fetch" (no message). Fix the underlying
        # cause by configuring AUGURA_SUPABASE_URL/AUGURA_SUPABASE_SERVICE_ROLE_KEY in prod.
        log.exception("storage_error", error=str(exc))
        return JSONResponse(
            status_code=500,
            content={
                "type": "https://augura.dev/errors/storage_error",
                "title": "Storage error",
                "status": 500,
                "detail": "the file storage operation failed",
                "code": "storage_error",
            },
            media_type="application/problem+json",
        )
